### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonathanong** [dollarshaveclub/e2e#1]
- [x] binary and all references should be `dsc-e2e` 
- [ ] add retry after support
- [x] make sure driver is a static property
- [x] add logging
- [x] test sauce labs
- [ ] write docs on optimizing circle jobs
- [x] validate all tests before running
- [x] add `slowThreshold` support
- [x] add `log()` support
- [ ] add `startTime` support
